// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppCacheAPI.Models;

public partial class IdeaDTO
{
    [Required]
    [StringLength(255)]
    public string Title { get; set; }

    [StringLength(5000)]
    public string Description { get; set; }

    [StringLength(7)]
    public string Color { get; set; }
}