// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AppCacheAPI.Models;

[Table("idea")]
[Index("UserId", Name = "IX_idea_user_id")]
public partial class Idea
{
    [Key]
    [Column("idea_id")]
    public int IdeaId { get; set; }

    [Required]
    [Column("title")]
    [StringLength(255)]
    public string Title { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("color")]
    [StringLength(50)]
    public string Color { get; set; }

    [Column("user_id")]
    public string UserId { get; set; }

    public virtual ApplicationUser User { get; set; }

    public virtual ICollection<CategoryIdea> CategoryIdeas { get; set; }

}