// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using AppCacheAPI.Models;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace AppCacheAPI.Data;

public partial class AppCacheDbContext : IdentityDbContext<ApplicationUser>
{
    public AppCacheDbContext(DbContextOptions<AppCacheDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Idea> Ideas { get; set; }
    public virtual DbSet<Category> Categories { get; set; }
    public virtual DbSet<CategoryIdea> CategoryIdeas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<Idea>(entity =>
        {
            entity.HasKey(e => e.IdeaId).HasName("idea_pkey");
        });

        modelBuilder.Entity<CategoryIdea>()
            .HasKey(ci => new { ci.CategoryId, ci.IdeaId });

        modelBuilder.Entity<CategoryIdea>()
            .HasOne(ci => ci.Category)
            .WithMany(c => c.CategoryIdeas)
            .HasForeignKey(ci => ci.CategoryId);

        modelBuilder.Entity<CategoryIdea>()
            .HasOne(ci => ci.Idea)
            .WithMany(i => i.CategoryIdeas)
            .HasForeignKey(ci => ci.IdeaId);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
